### ISSUE TITLE
Feature: Dropdown Disabled State

### ISSUE THREAD

**Issue by ryanomackey** [carbon-design-system/carbon-components-react#119]
It'd be nice if the `<Dropdown />` component had a 'disabled' state.

**Comment by paulbarr** [comment]
@hellobrian  We have need of this capability as well. 
If there is no one available to work on this and you have a pattern to follow for disbaling componenets we can do it and Pull Request it in. Please let me know

**Comment by chrisdhanaraj** [comment]
Looks like the visuals created the disabled state style, just never got implemented

http://carbondesignsystem.com/components/dropdown/style

This would need

1) CSS update on carbon-components
2) Prop update on carbon-components-react

**Comment by paulbarr** [comment]
If a change is being made here, there is another issue as well. 
Currently you can pass in 'selectedText' so that it initially selects one of the drop down items
However this only ever fires in the constructor, so you can not dynamically update what is in the drop down list and select something from that list. For our use case we need to dynamically update the content of the drop down - so we are looking for the code that uses 'selectedText' to be in willRecieveProps as well
