### ISSUE TITLE
FileUploader: can't attach the same file again when remove it before

### ISSUE THREAD

**Issue by shyfruan** [carbon-design-system/carbon-components-react#154]
The issue can be reproduced in storybook in Chrome.

1. Add 'Archive.zip'
![image](https://user-images.githubusercontent.com/29720673/28858892-7edde8f6-7786-11e7-9bb7-3af6904aa875.png)

2. Remove the file with delete icon, and cannot add 'Archive.zip' again

**Comment by shyfruan** [comment]
And 'onChange' function will not be called when remove seleted files.

**Comment by hellobrian** [comment]
Sorry this may not have been documented clearly enough, 
but removing the file with delete icon doesn't actually change the `FileList` object. 

If you check `evt.target.files`, you'll see that the `archive.zip` is still part of the FileList and cannot be removed. 

This is happening because the delete icon and `Filename` component that gets rendered is only for a rendering visual state.
 
You, the developer, have to write the code to actually change the `FileList` object and the component can represent that visual state of adding, removing and uploading.
