### ISSUE TITLE
Refactor Components with Form elements to have optional labels

### ISSUE THREAD

**Issue by eddiemonge** [carbon-design-system/carbon-components-react#168]
If you don't provide labelText for a checkbox, it will add `Provide checkbox label text`. Same for iconDescription. This is counter-intuitive. If they should be required then mark the propType as required. Otherwise, they should not be listed in defaultProps

**Comment by hellobrian** [comment]
Hey @eddiemonge, I can see why this is frustrating.
In most components, `defaultProps` are definitely required props and I would agree with you that these could be marked as `isRequired`.

With that said, I know this issue speaks to another issue we should be addressing too about limited composability. 

For example, with Checkbox: if you only want to render the `<input>`, you can't because you have to render the `div` wrapper, `label` and `input`. I'm guessing you were trying to use the Checkbox without the label, yet the label would still render. 

Is that correct?

**Comment by eddiemonge** [comment]
Yup. even using an empty string didn't seem to work since that evals to false

**Comment by hellobrian** [comment]
Will start refactoring `Checkbox` and other components that use Form elements so that `label` is optional and will either render itself or `null` - this will make it so that `labelText` props are not `isRequired` or needed in `defaultProps`

**Comment by marijohannessen** [comment]
This will be resolved in https://github.com/carbon-design-system/carbon-components-react/pull/301

**Comment by marijohannessen** [comment]
This is resolved now with #382
