### ISSUE TITLE
InteriorLeftNavItem needs more flexible children and href shouldn't be handled by the parent

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon-components-react#169]
InteriorLeftNavItem should be modified so the child (the link) is more customizable. Right now if you want to use `Link` inside an `InteriorLeftNavItem`.

**This code:**
```
<InteriorLeftNavItem id="nav-clusters" title="Clusters" href="clusters" label= {t('Clusters')} >
   <Link to="`${path}/clusters`" />
</InteriorLeftNavItem>
```

Turns into this HTML:
![pasted image at 2017_07_18 04_44 pm](https://user-images.githubusercontent.com/5447411/28981768-bc48cc90-7918-11e7-8a88-b0a9ae024ae1.png)

And it still ends up doing a full page reload, even though it's a link. It seems like the `to` in the `Link` is being ignored and the `href` in the parent is being used instead.

**Comment by jlengstorf** [comment]
I might be wrong, but this looks like it's not rendering the `Link` at all, but using the [default markup](https://github.com/carbon-design-system/carbon-components-react/blob/master/components/InteriorLeftNavItem.js#L54-L58) instead.

It looks like the Carbon `Link` component doesn’t support a `to` prop. If we drop in an `href` instead, it works:

```jsx
        <InteriorLeftNavItem href="#example-item-2A">
          <Link href="#component-link">Link Component Child</Link>
        </InteriorLeftNavItem>
```

<img width="802" alt="screencap-by-jlengstorf 123" src="https://user-images.githubusercontent.com/163561/29084989-5f74bcae-7c33-11e7-8e25-d8a4b90eb1fe.png">

With `to`, it _does_ still render a link, but without an `href` value:

```jsx
        <InteriorLeftNavItem href="#example-item-2A">
          <Link to="#component-link">Link Component Child</Link>
        </InteriorLeftNavItem>
```

<img width="781" alt="screencap-by-jlengstorf 124" src="https://user-images.githubusercontent.com/163561/29085042-8c7ebb1e-7c33-11e7-9e72-f08828f4dc9a.png">

All that being said, I can't duplicate the behavior of the code in the original bug. Is this a `react-router` `Link` component?

**Comment by marijohannessen** [comment]
Related https://github.com/carbon-design-system/carbon-components-react/issues/279

**Comment by alisonjoseph** [comment]
@marijohannessen The Carbon Link component appears to work as expected as far as I can tell, so I assume it doesn't work with react-router Link based on the related issue?

It doesn't make sense for the `label` and `href` to be required for the `InteriorLeftNavItem` since they appear to be ignored anyway if you add a link as a child.

**Comment by jlengstorf** [comment]
I think there may be a need to refactor `InteriorLeftNav` and its child classes to be far less opinionated. In Next.js, we get prop warnings because it adds a `tabIndex` and other props that violate the defined props for the Next.js `Link` component.

I'd also love to see this rolled up into a composite component that could work something like this:

```js
const navItems = [
  {
    label: 'Home',
    href: '/home',
  },
  {
    label: 'About',
    href: '/about',
  },
];

return <InteriorLeftNav items={navItems} />;
```

And a custom link component could also be supplied with:
```js
return <InteriorLeftNav items={navItems} linkComponent={Link} />;
```

It should still be _possible_ to build a left nav from its component parts (which should be extremely unopinionated), but for opinionated usage a composite component creates a better expectation of what is and isn't customizable.
