### ISSUE TITLE
Make the DetailPageHeader more composable

### ISSUE THREAD

**Issue by AnthonyOliveri** [carbon-design-system/carbon-components-react#186]
Possibly related to issue #147.

Currently, the DetailPageHeader includes a title, and accepts up to 4 additional child components: `Breadcrumb`, `Tabs`, `OverflowMenu`, and `Icon`. There are a few more components that we want to add to it on the developer console. I would open a pull request, but I am not sure how you guys would want this to be implemented.

For context, here is the prototype of what we are trying to create. Note the `Node` language tag and `View demo example` link, as well as the description below the title.

<img width="1220" alt="screen shot 2017-08-11 at 6 18 02 pm" src="https://user-images.githubusercontent.com/5459406/29235157-1eca536c-7ec2-11e7-9dad-8de8c352edf7.png">

**Comment by hellobrian** [comment]
Hey @AnthonyOliveri, in general, the most important criteria we look for in approving pull requests is making sure that the code doesn't have any breaking changes. 

You can see our full [contribution guidelines here](https://github.com/carbon-design-system/carbon-components-react/blob/master/CONTRIBUTING.md).

Specifically, the `DetailPageHeader` component is a bit tricky since there isn't one composition that works for everyone. 

Here's what you could do for now:

If you think you have a way to refactor `DetailPageHeader` so that it resolves your problem while not breaking any other scenarios we currently support, then make a pull request to `carbon-components-react` repo.

Otherwise, make a pull request to [carbon-addons-bluemix-react](https://github.com/carbon-design-system/carbon-addons-bluemix-react).

One thing I can do on my end:

- Ask my designers if they have any updated ideas about DetailPageHeader options. If there are multiple common patterns that we're seeing across IBM Cloud, then we can capture those compositions into React components.

P.S. To better help you out in the long run, can you tell me what team you work with?

**Comment by AnthonyOliveri** [comment]
Thanks for the feedback @hellobrian. I will try a pull request to modify `DetailPageHeader` first. Is there any documentation on how `carbon-addons-bluemix-react` works (how to contribute, how to add it to a project, etc)? I don't see it published on either npmjs.com or npm whitewater.

I work on the Developer Experience team in the Application Runtimes and Frameworks org. For more context on what we're working on, here is a screenshot of what the header currently looks like:

![screen shot 2017-08-14 at 10 40 55 am](https://user-images.githubusercontent.com/5459406/29279354-2359adb6-80dd-11e7-8339-8de4a31e6a0f.png)

And here is the prototype that shows how we want to change it (ignore the blue highlights):
https://ibm.invisionapp.com/share/S4BQP0SG2#/screens/232654490

![screen shot 2017-08-14 at 10 42 48 am](https://user-images.githubusercontent.com/5459406/29279430-6158a4a0-80dd-11e7-997c-51840db62d67.png)

**Comment by aagonzales** [comment]
Hi. I don't think this items belong in the detail page header itself. The DPH is (or should be according to the Bluemix criteria) a sticky component at the top of the page. Adding this bits of content to the header decreases the view port for the rest of the content on the page. Can it not just leave under/outside of the DPH? 

If you're keeping it in the header, do you have a recommended responsive strategy for how this content will collapse on scroll?

**Comment by ineedsubstance** [comment]
Hi, @aagonzales. 

For a little more context, the view that we are showing is a project detail view. Projects in our experience are how a user organizes their resources (apps or services). The project view is the place we see users coming back to build their app and we wanted to provide them with some extra info related to the project in the header. 

Projects include a language choice upon creation that we wanted to surface up. We are also using Starter Kit (services, UI use case, ) to get users started quickly, which includes a sample app that we want to link to and a short description of the use case that we also didn't want to lose.

We originally had this extra content in a module below the header which was taking up a lot of real estate and we our attempt to consolidate that content and make the main content area more actionable.

I was looking at the current CF app header for inspiration.

![screen shot 2017-08-14 at 12 50 27 pm](https://user-images.githubusercontent.com/3981381/29285021-9a484620-80f2-11e7-90ee-c32c7f738cf2.png)

---

Also, the idea was to not change the behavior of the header and to hide the breadcrumb and description when the user scrolls to mimic the current component.

![project_overview-blank-ipr](https://user-images.githubusercontent.com/3981381/29284924-3c14cef2-80f2-11e7-9537-76429185e254.png)

![project_overview-blank-ipr_scroll](https://user-images.githubusercontent.com/3981381/29284929-3f6cd130-80f2-11e7-8fd2-332f08b8c5b9.png)

---

Good question on the responsive strategy, and I can look to provide some screens for that as well.

**Comment by ineedsubstance** [comment]
FYI: We decided to remove the description from the project detail header.

**Comment by AnthonyOliveri** [comment]
I forgot to mention that I opened a pull request to implement these changes: #194.

**Comment by marijohannessen** [comment]
Resolved
