### ISSUE TITLE
Multiple button actions in modal footer

### ISSUE THREAD

**Issue by hanhansen** [carbon-design-system/carbon-components-react#188]
Our modal design includes a primary action, a secondary action and then a cancel action. 

'Save and view'
'Save'
'Cancel'

Would this modal ever support multiple actions like what is displayed above? If so, I can put a PR for this.

**Comment by hellobrian** [comment]
I'll leave this up to the designers but I would advise against 3 buttons in a Modal just because I'm not sure if that will all fit in a mobile view or narrow viewport. 

![image](https://user-images.githubusercontent.com/4185382/29286852-bdc2a1c4-80f0-11e7-8ab5-de4ced1b53b0.png)

[Source](http://carbondesignsystem.com/components/modal/style)

**Comment by aagonzales** [comment]
Yes, @hellobrian you are correct. We do not advice putting three buttons here. If anything I would recommend changing "cancel" to "view" and relying on the x in the top right as a close/cancel action.
