### ISSUE TITLE
Overflow menu outline expanded by dropdown in Mozilla

### ISSUE THREAD

**Issue by tim-zhong** [carbon-design-system/carbon-components-react#196]
In Chrome:
<img width="326" alt="screen shot 2017-08-21 at 10 36 23 am" src="https://user-images.githubusercontent.com/10435612/29523982-a764611c-865c-11e7-9ca0-dbc2c0ed81dc.png">

In Firefox:
<img width="441" alt="screen shot 2017-08-21 at 10 26 00 am" src="https://user-images.githubusercontent.com/10435612/29523993-b47276c8-865c-11e7-8273-a1ea9d98d830.png">

**Comment by joshblack** [comment]
Hi there! Since this is related to the CSS of the component [reference](https://stackoverflow.com/questions/10662902/css-outline-different-behavior-behavior-on-webkit-gecko), and not the React.js bindings, moved this issue over to: https://github.com/carbon-design-system/carbon-components/issues/475

Feel free to re-open if you feel like that doesn't address your core concern!
