### ISSUE TITLE
Feature: support non-expandable rows in NestedTable

### ISSUE THREAD

**Issue by aprilwebster** [carbon-design-system/carbon-components-react#202]
Have run into an example where a table with expandable rows is necessary for only a subset of the rows - additional data isn't available for all rows.

**Comment by chrisdhanaraj** [comment]
Hey @aprilwebster - the same scenario should work, you have to create an array that properly describes your data. In the `NestedRows` example, because my expanded rows are 1:1 with the parent rows, I can use a `map` function to iterate over the dataset and create the JSX. In the case of only the occassional expanded row, you'll have to use a `for` loop and push data into a new array to get a properly flattened array (React can't render two JSX elements without a parent, which doesn't work in a table)
