### ISSUE TITLE
NumberInput  shown incorrectly.

### ISSUE THREAD

**Issue by bjqw** [carbon-design-system/carbon-components-react#2135]
<NumberInput style={{width:"40px"}}/>

When the invalidText shows, the up down button move to another place.
![image](https://user-images.githubusercontent.com/40851563/55374357-bf739d00-553a-11e9-8459-8ff6852c2917.png)
![image](https://user-images.githubusercontent.com/40851563/55374381-d619f400-553a-11e9-9869-3bc97014c04b.png)

**Comment by emyarod** [comment]
hi @bjqw thanks for reporting this! I believe this is because the number controls are positioned with `position: absolute`, but the width of the input field has been reduced in your example. to get around this you would just need to reposition the number control accordingly (it may be easier with `position: relative` in your example)

**Comment by dakahn** [comment]
Closing this as resolved. I'll totally reopen if that's not the case 🏄
