### ISSUE TITLE
Module Header has changed

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-components-react#26]
Module Header used to be a container section 
![screen shot 2017-06-13 at 4 19 51 pm](https://user-images.githubusercontent.com/1449523/27105155-2c33019e-5054-11e7-8595-300ca4d5e93c.jpg)

Now it's wrapping the children inside of an `<h1>`
![screen shot 2017-06-13 at 4 21 49 pm](https://user-images.githubusercontent.com/1449523/27105251-7ed952b8-5054-11e7-9ebb-f2af84af2d5d.jpg)

The component should be open to flexibility.
Most of the time it's just going to be a normal h1, but sometimes additional UI will be introduced like buttons and such.

---

- [ ] make ModuleHeader component flexible for html children

**Comment by hellobrian** [comment]
Thanks for pointing this out.

Also, we also recognize that we shouldn't  be using `<h1>` and other heading tags in our components for visual styling since it can lead to confusing screen-reader navigation (see https://github.com/carbon-design-system/carbon-components/pull/154#issue-233643947 for more details). 

If no one assigns themselves to this in time, feel free to assign yourself to this issue and submit a PR.

**Comment by jzhang300** [comment]
Should the styling be all the same, but the semantic html be up to developer?

**Comment by hellobrian** [comment]
☝️  Yes. That is correct.

**Comment by joshblack** [comment]
Hi @jzhang300! Just wanted to check back in on this issue to see if the original question/concern has been addressed? I know you've submitted a couple of PRs related to Module Header, wanted to see if any of those addressed this as well.

Thanks again for taking the time to make an issue! 🎉
