### ISSUE TITLE
Firefox only:  Reddish border around required input element 

### ISSUE THREAD

**Issue by HeatherZh** [carbon-design-system/carbon-components-react#290]
<img width="1270" alt="screen shot 2017-10-24 at 11 20 52 am" src="https://user-images.githubusercontent.com/217946/31952128-d90d1a32-b8ad-11e7-9014-6dd28366f411.png">

"Required" TextInput component such as:
<TextInput 
  className={nameFieldClass} 
   labelText={nameLabel} 
   placeholder={namePlaceholder} 
   onChange={this.onNameChanged.bind(this)}
    value={this.state.name} required/>

would render a reddish border around the element in Firefox only.

**Comment by HeatherZh** [comment]
This is similar to what was reported in #141.

**Comment by HeatherZh** [comment]
box-shadow: unset;    seems to help

**Comment by joshblack** [comment]
Thanks so much for reporting this issue @HeatherZh! Like you noted, it's totally the same issue that's in #141. I'm going to consolidate the two issues into a single implementation task in #304 so that we can tackle them at the same time 😄 

If you have any questions or concerns, feel free to reply on GitHub or in the #carbon-react channel on Slack! In addition, if you believe I'm closing this issue erroneously feel free to re-open with the rationale.

Have a great day!
