### ISSUE TITLE
Tooltip not working in React 16

### ISSUE THREAD

**Issue by shjunmiao** [carbon-design-system/carbon-components-react#300]
TypeError
Cannot read property 'getBoundingClientRect' of null

How to reproduce:  import the Tooltip and copy the code from Storybook and try to render.
https://codesandbox.io/s/xv4w4yx0oz

**Comment by joshblack** [comment]
Thanks so much for opening this @shjunmiao! And thanks so much for providing a repro link, it helps us a ton 😄 

Going to label this as a bug right now and try and add it to either the tail-end of our current sprint, or place it in our queue for next sprint (starts next week). We always except PRs so if the fix is simple and we're just not getting to it in time, feel free to PR and we'll gladly merge it in!

Happy Halloween! 👻
