### ISSUE TITLE
Search small extra X  showing in ie Only

### ISSUE THREAD

**Issue by shjunmiao** [carbon-design-system/carbon-components-react#316]
![capture](https://user-images.githubusercontent.com/31211767/32546933-85031bf4-c478-11e7-8bd7-d106ffda4ec0.PNG)
in ie, there is a extra small X when render Search

http://react.carbondesignsystem.com/?selectedKind=Search&selectedStory=small&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by joshblack** [comment]
Hi there! 👋 

Thanks so much for taking the time to open this issue. Since this is a CSS change that's needed in `carbon-components`, I went ahead and made this issue https://github.com/carbon-design-system/carbon-components/issues/412 on that repo to handle this issue.

I'm going to go ahead and close this issue in preference for that, but if you feel like that issue doesn't address your concerns feel free to re-open with any additional information that might be different!

**Comment by JoshDKing** [comment]
I also saw this yesterday working in Microsoft Edge!

**Comment by joshblack** [comment]
Yay! Glad to hear @JoshDKing 🎉
