### ISSUE TITLE
ClickListener -component can be exposed to user as a direct Component.

### ISSUE THREAD

**Issue by sandhya-r-reddy** [carbon-design-system/carbon-components-react#364]
Currently ,ClickListener component is exposed to user as an internal component.It is a useful component which can be used in many scenarios.
It can be imported as ``` import ClickListener from 'carbon-components-react/cjs/internal/ClickListener';```

From the recent folder structure change to the carbon-components-react, upgrading to latest version, breaks our code as we are using absolute path in import.

 If we are exposing these components in internal to user, why not as direct components.
It would be nice if we can import this as a ``` import ClickListener from 'carbon-components-react'```

**Comment by joshblack** [comment]
Hi @sandhya-r-reddy! Thanks so much for taking the time to make this issue 😄 

Totally agreed that internal utilities can potentially be useful to consumers, I think the group hesitates to expose some in an official capacity until they have more eyes on them to make sure they're prod-ready.

Regardless, you can still rely on the path to the internal component by using `lib` instead of `cjs`. We moved to supporting `lib` in a recent release, and this structure will always be present as an output of our build step. This makes sure that we don't tie in the format of our generated code to the folder name, so it should help with your specific use-case. e.g., `import ClickListener from 'carbon-components-react/lib/internal/ClickListener`.

**Comment by joshblack** [comment]
Closing this for now, unfortunately dealing with the additional surface area of internal components is too much for the group to take on right now. Groups can 100% still use them if they are useful, but they won't follow the same guarantees that using the publicly available components have 👍
