### ISSUE TITLE
Carbon Components for React 15.x

### ISSUE THREAD

**Issue by DmitriWolf** [carbon-design-system/carbon-components-react#407]
## Not the latest and greatest

I wish we were great. Like really great. So great that we always used the latest version of everything. 

### Sigh...

Alas, we cannot keep up. Some of our apps use earlier versions of React. A full version earlier. 
React is now on 16, but our app is on version 15. We are a full [3 months](https://reactjs.org/blog/2017/09/26/react-v16.0.html) behind the times.

## Require Peer Dependency of React 15

Because of [these two lines](https://github.com/carbon-design-system/carbon-components-react/blob/master/package.json#L85-L86), I cannot use Carbon in its latest version (which I need because of the [Tooltip functionality](https://github.com/carbon-design-system/carbon-components-react/pull/395) that was just added). Are there features in Carbon that absolutely must have React 16? If so, can they be refactored to work with React 15? If not, then this should be an easy fix.

Help me @tw15egan . You're my only hope. Except maybe @joshblack @alisonjoseph or @marijohannessen .

**Comment by eddiemonge** [comment]
React 16 brings things like Fragments and Portal. Portal will be good for modals and other things that get added to the page on the fly.

You should be able to upgrade your app easily according to https://reactjs.org/blog/2017/09/26/react-v16.0.html

> With minor exceptions, if your app runs in 15.6 without any warnings, it should work in 16.

**Comment by joshblack** [comment]
Hi @DmitriWolf! Totally understand your position. On a side note, does your install step fail because of the peerDependency mismatch? I had an assumption that it would only throw a warning, but that could easily be wrong.

**Comment by DmitriWolf** [comment]
@joshblack We are using `npm shrinkwrap --dev` which locks our dependency tree as suggested in [this article](https://docs.npmjs.com/files/package-locks) and accepted as best practice. Lock packages require dependencies to be met or they throw errors, for good reason.

Is there any issue with keeping the dependency down to, say, React 15.2 ? 
Does anything break?

**Comment by DmitriWolf** [comment]
## support React16 for test
@joshblack I see that these dependencies were upped because of [this issue](https://github.com/carbon-design-system/carbon-components-react/pull/366). I like the work you did there and see the point. So how can we keep that valuable work and still have Carbon be backwards compatible with recent versions of React?

That issue, if I understand correctly, upped the versions of Enzyme so they work with React 16. Would it be possible to keep an earlier version of React as a dev-dependency without breaking your tests?

**Comment by joshblack** [comment]
@DmitriWolf totally understand the requirement for a lockfile! I meant more-so the following wouldn't throw:

https://asciinema.org/a/RpsVlfEp4tw3JwT1lIiaMgZQF

So am curious what part of your process is making the install error out versus warning like it did in the above clip.

---

With respect to our `peerDependency` on React v16.x, we're looking towards updating our internal babel usage so that we can make use of the new fragment syntax, in addition to supporting the latest portal features that the new release provides. As a result, backwards support will get more and more flaky depending on the component in use.

I really do apologize about the version mismatch, we really did try and stall the update to React 16 initially, and then have been stalling with using React 16-specific features. Unfortunately, we just don't have the development team to support both the React v16 and React v15 versions of the library. However, as of the latest 5.x versions for this project, if you have React v15 then the components should still work, unless some error is being thrown during the install stage.

Hope this helps, feel free to respond with any follow-up questions or if something I'm saying is clearly wrong 😅

**Comment by DmitriWolf** [comment]
@joshblack Thank you so much for your attention to this issue and for that video.
I will take a second look at options on my end and get back to you.

**Comment by joshblack** [comment]
@DmitriWolf of course! Let me know if we can help out in any way 😄 

Going to close this issue for now, feel free to re-open though if you want to continue this discussion!

**Comment by DmitriWolf** [comment]
@joshblack I wanted to circle back with you to share my solution.

## Escaping Peer Dependency Hell
You got me on the right track with that video. I saw `package.lock` file in there and realized you are using a more recent version of Node than we use for the project we are working on. We use `node 6.9.5` which comes with `npm 3.10.10`. 

It says here that npm can handle peer-dependencies since npm 1.2.10 in Node.js 0.8.19, but that's not what we are observing! 

What I finally did was to use `nvm use 8` to temporarily use node 8, then I followed your steps, `npm i` to make the `package.lock` file, then `npm shrinkwrap --dev` simply renamed it, and I'm done! Well.. sort of, there was another error to fix, but that was simple enough. Switch back with `nvm use 6` and that's that!

Again, thank you for your help.

**Comment by joshblack** [comment]
Awesome @DmitriWolf! Glad it worked out. Do you think this info would be helpful as part of the documentation for this repo?

**Comment by DmitriWolf** [comment]
I do. I wrote a blog on the company's private network. Let me PM that to you and you can copy as you think is appropriate.
