### ISSUE TITLE
DataTable components not importing properly

### ISSUE THREAD

**Issue by chr1stinayan** [carbon-design-system/carbon-components-react#476]
When importing components from DataTable.js, the webpage fails to render (getting a blank screen).

I'm using ```import { DataTable, DataTableBody } from 'carbon-components-react/lib/DataTable'``` to grab the components based on this example https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/DataTable/DataTable-story.js#L116

**Comment by tw15egan** [comment]
Hey @chr1stinayan, it would be helpful to us if you provide more information and follow the issue template. What version of the components are you on? Can you reproduce this in CodeSandbox?

**Comment by asudoh** [comment]
An approach to isolate the problem is getting a dump of virtual DOM - Seems that React DevTools as well as https://reactjs.org/docs/test-renderer.html does that. Also, given you seems to be using ECMAScript module - Wondering if using `es` directory instead of `lib` directory makes any difference (`lib` has CJS module where as `es` has ES module). Thanks!

**Comment by chr1stinayan** [comment]
Managed to resolve this by following this example: https://codesandbox.io/s/6lyvq4nozw, I was trying to use DataTable and DataTableBody without the DataTableContainer and DataTableHead components which seemed to fix it

**Comment by asudoh** [comment]
@chr1stinayan Great that you figured it out yourself! 🙂 For future reference, `*-story.js` in Carbon React codebase demonstrates how to use components. If you clone carbon-components-react repo, running `npm i; npm run storybook` will demonstrate how those `*-story.js` work.
