### ISSUE TITLE
Dropdown does not use onClick prop

### ISSUE THREAD

**Issue by AndySeymour2904** [carbon-design-system/carbon-components-react#676]
> Describe in detail the issue you're having.
I have a dropdown in a component which is refreshing when it receives fresh data, this forces a reload of the dropdown and it to close if it is open.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?
Be able to use onClick and open prop to store state in my own component so I can re-render my component and keep the dropdown open.

I think there needs to be an onOpen and/or onClose callback for the dropdown component and remove the onClick prop

**Comment by s100** [comment]
* I added `onOpen` and `onClose` to `Dropdown` [just a few days ago](https://github.com/carbon-design-system/carbon-components-react/pull/660).
* It seems as if it is intentional that clicking an option in the dropdown causes it to close. I've never seen a dropdown which doesn't work this way.
* As for the issue with the dropdown not respecting the updated value of the `value` prop while the dropdown is open, I don't know a whole lot about that, sorry.

**Comment by AndySeymour2904** [comment]
@s100 Ahh perfect, that should probably cover my use case. I'll close this issue
