### ISSUE TITLE
[Regression] MultiSelect does not un-select properly

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#707]
Seems like we might have had a regression recently with the way MultiSelect handles selection. Including a gif to reproduce below:

![kapture 2018-03-13 at 9 08 48](https://user-images.githubusercontent.com/3901764/37346741-2a770e9c-269e-11e8-842d-7ff4450911b7.gif)

**Comment by rezak-otmani** [comment]
hey @joshblack I noticed that the origin of the issue is the fact that you re-insert the removed items systematically on the `componentWillReceiveProps` hook (cf. https://github.com/carbon-design-system/carbon-components-react/blob/master/src/internal/Selection.js#L23).

Is there any reason that I am missing for having this code? If no, then I think it is safe to go ahead and remove it.

**Comment by joshblack** [comment]
Hi @rezak-otmani! Definitely seems like the culprit here. Would be worthwhile to see if removal causes any regressions, since I think you're right that this is the root cause of the issue.

**Comment by rezak-otmani** [comment]
hi @joshblack   I have opened a PR #761,  it appears that `ComponentWillReceiveProps` impacts only MultiSelect
