### ISSUE TITLE
Console Object.values error loading page in IE11

### ISSUE THREAD

**Issue by flyHe** [carbon-design-system/carbon-components-react#719]
## Detailed description

> Describe in detail the issue you're having.

We updated the carbon-components-react to the lastest version recently, but it Console Object.values error loading page in IE11, and we do not use the `Object.values` in our code but we find it has been used in carbon-components-react, we just polyfill the Object.values in our code, but we think it is an issue that carbon-components-react should fix.
> Is this a feature request (new component, new icon), a bug, or a general issue?

a bug in ie11

> Is this issue related to a specific component?

ie11

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
IE1
> What version of the Carbon Design System are you using?

5.31.0
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code

<img width="673" alt="screen shot 2018-03-16 at 11 56 50 am" src="https://user-images.githubusercontent.com/10543919/37503061-256b7846-2911-11e8-94cc-d72c3b03e156.png">

* Notes

**Comment by asudoh** [comment]
@flyHe Carbon requires some polyfills to run on older browsers. For `carbon-components-react`, the list is maintained in https://github.com/carbon-design-system/carbon-components-react/blob/master/.storybook/polyfills.js. Thanks!

**Comment by flyHe** [comment]
@asudoh Okay, got it. But I am curious why carbon-components-react can not do these polyfill in carbon side, people can not find the changes in storybook every times they update the version, often we just upgrade the carbon-components-react to one version in our own side.And some errors will occur if we do not see the polyfill changes

**Comment by flyHe** [comment]
@asudoh one more question, what browsers do carbon-components-react support now?

**Comment by joshblack** [comment]
> But I am curious why carbon-components-react can not do these polyfill in carbon side

In this case, we don't want to double-include polyfills since some teams use packages like `babel-preset-env` to polyfill their environment based on usage. In the future, we're hoping to provide a polyfill package that you can use that will be automatically updated with whatever is the latest polyfill needed 👍 

> what browsers do carbon-components-react support now?

For browser support, you can see our browserslist config [here](https://github.com/carbon-design-system/carbon/blob/master/packages/browserslist-config-carbon/index.js#L4). It references the browser requirements of IBM Cloud, which are [here](https://console.bluemix.net/docs/overview/prereqs.html#prereqs). Hope that helps!

**Comment by flyHe** [comment]
@joshblack Thanks.
yes, we have used babel-preset-env to polyfill, I will give attention to the polyfills list when we upgrade the carbon-components-react, and add it in our side. If not catch the polyfill requirement, it will take a risk.
