### ISSUE TITLE
Allow independent Accordion inside AccordionItem

### ISSUE THREAD

**Issue by pazbu** [carbon-design-system/carbon-components-react#814]
## Brief description

 I am trying to create an expandable section which has an Accordion inside it.
The expandable section is implemented using a single AccordionItem which opens the section.

The issue: the inner AccordionItems inherit the CSS classes of the outer AccordionItem, and thus are also expanded if the outer ancestor AccordionItem is expanded. 

The inner Accordion is therefore "frozen" due to its parent AccordionItem.

## Steps to reproduce the issue

1. Add an Accordion inside an AccordionItem
2. Expand the outer AccordionItem
3. The inner Accordion items are also expanded.

![screen shot 2018-04-16 at 11 41 02](https://user-images.githubusercontent.com/20580551/38798799-49febf2a-416b-11e8-9422-7820c0b1bc83.png)

**Comment by joshblack** [comment]
Hi @pazbu! 👋 Thanks so much for taking the time to make this issue 🙂

Unfortunately, nesting accordions within accordion items isn't a UX pattern that is supported by this library currently. Closing this for now, but if you feel like you have a valid design case for this pattern, feel free to comment on this issue!

**Comment by Dani7B** [comment]
In my case I'm navigating a folder tree, where leaves are documents; therefore having nested accordion would make sense to me, instead of having N number of pages to go through to get to a document. I believe it's a UI experience the user is used to and I cannot think of any reason why nesting shouldn't be allowed.
<img width="431" alt="schermata 2018-10-13 alle 21 49 23" src="https://user-images.githubusercontent.com/1493426/46909397-11474d00-cf32-11e8-804a-a4ba950e9564.png">

As I mentioned in https://github.com/IBM/carbon-components/issues/1262, **the fix would be fairly simple and wouldn't impact the regular non-nested behavior** (It's just CSS).

**Comment by jeanservaas** [comment]
@asudoh we have the foundation with this from security — we'd just keep the same vertical heights and the same left key alignments to achieve the nesting:
https://pages.github.ibm.com/security/carbon-addons-security/?knob-buttons.primaryButton.label=Save&knob-buttons.secondaryButton.label=Cancel&knob-buttons.closeButton.label=Close&knob-className=class&knob-iconDescription=Close%20notification&knob-subtitle=2%20users%20have%20been%20removed&knob-actionButtonLabel=Undo&knob-title=Notification%20title&selectedKind=Application%7CAccordion&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=%40storybook%2Faddon-a11y%2Fpanel

**Comment by chrisconnors-ibm** [comment]
@Dani7B the Open Source model we're operating under assumes teams out in the world who need specific deviations from existing components design, develop, and submit them back for consideration to include in our master branch. It's the only way we can scale our system to accomodate the breadth of needs in our organization. so if there are immediate needs by external teams, they are encouraged to create issues, design and build what they need, and submit them back to us in a pull request.

@joshblack is correct this is not a capability or pattern we intend to support with the accordion control.

Right now we haven't implemented a tree control in any of our frameworks, and doing so within our teams resources would be subject to the priorities of our already over-subscribed timeline.

**Comment by chrisconnors-ibm** [comment]
… should we add this to our list of components it's likely it would be delivered in the new IBM Design Language rather than the prior 'Cloud' style carbon expressed by default, and it wouldn't be in a production state until the Carbon X timeframe _at best_.

**Comment by Dani7B** [comment]
Hi @chrisconnors-ibm. Thanks for replying.
So, taken all into consideration, would you advise me to fork, branch and create a pull request?
I could definitely do that (it's actually a very slight change to the CSS that would not impact single level accordions) if you don't feel like a nested accordion is something that goes against some leading design principle.

P.S. I understand HTLM is a very powerful mark-up language and I've always believed I could stuff anything I like inside the content portion of an accordion or a tab, but if we decide against this idea, I believe we should specify that somewhere so that people are aware of how the component is meant to be used. :-)
