### ISSUE TITLE
Import Carbon Stories into New Project's Storybook

### ISSUE THREAD

**Issue by scottvincent** [carbon-design-system/carbon-components-react#875]
## Detailed description

> Describe in detail the issue you're having.

I have a Storybook in my project that I'm using with my own components. I'd like to include all of Carbon's existing stories in my storybook. So when theming, and developing you can see how changes affect the carbon stories. 

Instead of writing out and maintaining stories for all the stock carbon components again myself, I'd like to include `carbon-components-react` `master` branch as a devDependency and reference all the component *-story.js files for use in my own storybook. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

New feature, or documentation of existing method

> Is this issue related to a specific component?

All components

> What did you expect to happen? What happened instead? What would you like to see changed?

Importing all component -story.js files would display them in storybook under my own project's stories.

> What version of the Carbon Design System are you using?

4.49.0 

## Steps to reproduce the issue

1. Include `"carbon-components-react-master": "carbon-design-system/carbon-components-react#master"` as a devDependency in `package.json`
2. In your project's `.storybook/config.js` find all of the -story.js files in the carbon-components-react-master.

```
function loadStories() {
  // Project Stories located in component folders
  const req = require.context('../src/components', true, /\-story\.js$/);
  req.keys().forEach(filename => req(filename));

  // Pull all the stories from carbon-components-react-master
  const reqCarbon = require.context('carbon-components-react-master/src/components', true, /\-story\.js$/);
  reqCarbon.keys().forEach(filename => reqCarbon(filename));
}
```

## Additional information

When doing this, the following error appears in the storybook. 

![image](https://user-images.githubusercontent.com/4621427/39880216-130a3fb0-544b-11e8-8737-53374284c1bc.png)

**Comment by joshblack** [comment]
Hi @scottvincent! 👋 Thanks for taking the time to make an issue, especially for such an interesting use-case 🙂 The error that you're seeing is most likely due to `node_modules/carbon-components-react` not being included in any babel compilation step for your project. Would recommend adding it to your `babel-loader` config paths in order for it work as expected.

Looking forward, it is unlikely that we would invest the time to ship a transpiled version of our stories so this would be the best path moving forward. If you feel like there is an alternative solution, let us know!

Going to close this for now, feel free to re-open if your issue wasn't addressed 👍
