### ISSUE TITLE
React 17 migration path

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon-components-react#977]
A few months ago, the React team announced their plans to remove the `UNSAFE`-prefixed component lifecycle methods in version 17. Several of the carbon components use these soon-to-be deprecated methods, but there is a path for gradual migration to React 17. Are there any plans in the works for this move? The React team has also already outlined [several new component lifecycle methods that can be used](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html).

Related thread in [Slack](https://ibm-research.slack.com/archives/C2K6RFJ1G/p1528318660000299)

**Comment by joshblack** [comment]
Hi @emyarod! 👋 There are definitely plans to move away from the unsafe lifecycle methods called out in 16.3. No work has been started towards refactoring away from them as of yet, but there has been work into making sure that all the unsafe component lifecycle methods have been prefixed as such.

In addition, for code reviews we're starting to be more restrictive on lifecycles that can be used to deliver features or fix bugs 👍 

We went ahead and added `React.StrictMode` to our dev environment, as well, so that we can be fully aware of any components that will cause troubles in the next major release of react 😄

**Comment by emyarod** [comment]
Thanks for the info @joshblack, it's good to know that there are plans and actions being taken to stay aligned with the latest React versions! If the migration effort would require additional help from the community I would love to help contribute

**Comment by asudoh** [comment]
Great thanks @emyarod - Definitely help is welcome, e.g. `cWRP` -> `gDSFP` migration!

**Comment by emyarod** [comment]
And this might be worth taking a look at: [the React team just published a blog post yesterday about `gDSFP`](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html)
